FROM openjdk:8
RUN mkdir -p /opt/module/gmall-flink/rt_applog/
COPY . /opt/module/gmall-flink/rt_applog
WORKDIR /opt/module/gmall-flink/rt_applog
CMD ["java", "-jar", "gmall2020-mock-log-2020-12-18.jar"]
